version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    labels:
      - "traefik.frontend.rule=Host:traefik.gravitybudapest.com"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=admin:$$apr1$$XS0rRPa/$$GylsDtyB.l6WiQFUQkqnz/"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
networks:
  default:
    external:
      name: traefik
